"use client";

import React, { useState } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import EnquiryModal from "@/components/EnquiryModal";
import FloatingActions from "@/components/FloatingActions";

interface FAQItem {
  question: string;
  answer: string;
}

const faqData: FAQItem[] = [
  {
    question: "Are all Siddhivinayak Developers projects MahaRERA registered?",
    answer: "Yes. In compliance with the Real Estate Regulation and Development Act, all our projects are fully registered with MahaRERA. The specific registration numbers are clearly stated on individual project detail pages and marketing materials.",
  },
  {
    question: "Do you offer customization in residential floor layouts?",
    answer: "Yes, we support layout modifications during the early stages of construction. Discerning clients can merge rooms, adjust plumbing outlets for bespoke kitchens, or select alternate premium materials, subject to structural safety clearance from our engineering team.",
  },
  {
    question: "What is your typical timeline for completing society redevelopment projects?",
    answer: "A standard redevelopment project (from vacation of existing premises to structural handovers) takes approximately 24 to 30 months. This timeline includes planning clearances, structural casting, and finishing checks to ensure Grade-A execution standards.",
  },
  {
    question: "How can I book a private site visit or consultation?",
    answer: "You can request a site visit by filling out the enquiry form on our contact panel or clicking 'Request Call Back'. Our Relationship Managers will reach out to you within 15 minutes to schedule a luxury vehicle pick-up and guided tour.",
  },
  {
    question: "What facilities are provided in your grade-A commercial developments?",
    answer: "Our commercial properties (like Siddhivinayak Lumina) come equipped with modern curtain-wall facades, high-speed fiber backbones, automated mechanical car parking towers, LEED Gold energy efficiency elements, and independent VRV climate zones.",
  },
  {
    question: "How are the legal titles and land rights verified?",
    answer: "We ensure absolute transparency in ownership. Every project is backed by a clean search report generated by leading legal counsel, detailing clear title titles for at least 30 years. All documents are available for verification at our head office.",
  }
];

export default function FAQPage() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedProject, setSelectedProject] = useState("");
  const [modalSubject, setModalSubject] = useState("");
  const [openIndex, setOpenIndex] = useState<number | null>(0); // Default open first item

  const openModal = (project: string = "", subject: string = "") => {
    setSelectedProject(project);
    setModalSubject(subject || "FAQ Lead");
    setIsModalOpen(true);
  };

  const closeModal = () => {
    setIsModalOpen(false);
  };

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <>
      <Header openModal={openModal} />

      <main style={{ backgroundColor: "var(--bg-primary)", minHeight: "100vh", paddingTop: "140px", paddingBottom: "80px" }}>
        <div className="container" style={{ maxWidth: "800px" }}>
          <div className="text-center" style={{ marginBottom: "50px" }}>
            <span className="section-subtitle">COMMON QUERIES</span>
            <h1 className="section-title" style={{ fontSize: "36px" }}>Frequently Asked Questions</h1>
            <p style={{ color: "var(--text-muted)", fontSize: "14px", fontWeight: 300 }}>
              Find answers to core legal, booking, customization, and timeline details.
            </p>
          </div>

          {/* FAQ Accordion List */}
          <div style={{ display: "grid", gap: "20px" }}>
            {faqData.map((faq, idx) => {
              const isOpen = openIndex === idx;
              return (
                <div 
                  key={idx} 
                  style={{
                    backgroundColor: "var(--bg-surface)",
                    border: "1px solid var(--border-color)",
                    padding: "24px",
                    transition: "var(--transition-smooth)"
                  }}
                >
                  <button
                    onClick={() => toggleFAQ(idx)}
                    style={{
                      width: "100%",
                      background: "transparent",
                      border: "none",
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      textAlign: "left",
                      cursor: "pointer",
                      padding: 0,
                      fontFamily: "var(--font-serif)",
                      fontSize: "18px",
                      fontWeight: 600,
                      color: isOpen ? "var(--gold)" : "var(--text-white)",
                      transition: "color 0.2s ease"
                    }}
                  >
                    <span>{faq.question}</span>
                    <span style={{ 
                      fontSize: "22px", 
                      lineHeight: "1", 
                      color: "var(--gold)",
                      transform: isOpen ? "rotate(45deg)" : "rotate(0deg)",
                      transition: "transform 0.25s ease",
                      marginLeft: "15px"
                    }}>
                      +
                    </span>
                  </button>
                  
                  <div 
                    style={{
                      maxHeight: isOpen ? "300px" : "0px",
                      overflow: "hidden",
                      opacity: isOpen ? 1 : 0,
                      transition: "max-height 0.35s cubic-bezier(0.16, 1, 0.3, 1), opacity 0.35s ease",
                      marginTop: isOpen ? "15px" : "0px"
                    }}
                  >
                    <p style={{ 
                      color: "var(--text-muted)", 
                      fontSize: "14px", 
                      lineHeight: "1.7",
                      margin: 0,
                      fontWeight: 300 
                    }}>
                      {faq.answer}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Call to action panel */}
          <div 
            style={{ 
              backgroundColor: "var(--bg-secondary)",
              border: "1px solid var(--border-color)",
              padding: "40px",
              textAlign: "center",
              marginTop: "60px"
            }}
          >
            <h3 style={{ fontFamily: "var(--font-serif)", fontSize: "22px", color: "var(--text-white)", marginBottom: "10px" }}>
              Have a Specific Inquiry?
            </h3>
            <p style={{ color: "var(--text-muted)", fontSize: "14px", fontWeight: 300, marginBottom: "25px" }}>
              Our dedicated support team is available to assist you with bespoke requests.
            </p>
            <button className="btn btn-primary" onClick={() => openModal("", "FAQ Help Desk Request")}>
              Connect with executive
            </button>
          </div>
        </div>
      </main>

      <Footer />

      <EnquiryModal 
        isOpen={isModalOpen} 
        closeModal={closeModal} 
        selectedProject={selectedProject}
        subject={modalSubject}
      />
      <FloatingActions />
    </>
  );
}
