"use client";

import React, { useState } from "react";

interface FAQItem {
  question: string;
  answer: string;
}

const faqData: FAQItem[] = [
  {
    question: "Are all Siddhivinayak Developers projects MahaRERA registered?",
    answer: "Yes. In compliance with the Real Estate Regulation and Development Act, all our projects are fully registered with MahaRERA. The specific registration numbers are clearly stated on individual project detail pages and marketing materials.",
  },
  {
    question: "Do you offer customization in residential floor layouts?",
    answer: "Yes, we support layout modifications during the early stages of construction. Discerning clients can merge rooms, adjust plumbing outlets for bespoke kitchens, or select alternate premium materials, subject to structural safety clearance from our engineering team.",
  },
  {
    question: "What is your typical timeline for completing society redevelopment projects?",
    answer: "A standard redevelopment project (from vacation of existing premises to structural handovers) takes approximately 24 to 30 months. This timeline includes planning clearances, structural casting, and finishing checks to ensure Grade-A execution standards.",
  },
  {
    question: "How can I book a private site visit or consultation?",
    answer: "You can request a site visit by filling out the enquiry form on our contact panel or clicking 'Request Call Back'. Our Relationship Managers will reach out to you within 15 minutes to schedule a luxury vehicle pick-up and guided tour.",
  },
  {
    question: "What facilities are provided in your grade-A commercial developments?",
    answer: "Our commercial properties (like Siddhivinayak Lumina) come equipped with modern curtain-wall facades, high-speed fiber backbones, automated mechanical car parking towers, LEED Gold energy efficiency elements, and independent VRV climate zones.",
  },
  {
    question: "How are the legal titles and land rights verified?",
    answer: "We ensure absolute transparency in ownership. Every project is backed by a clean search report generated by leading legal counsel, detailing clear title titles for at least 30 years. All documents are available for verification at our head office.",
  }
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0); // Default open first item

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="faq-section scroll-offset" style={{ padding: "100px 0", backgroundColor: "var(--bg-secondary)" }}>
      <div className="container" style={{ maxWidth: "800px" }}>
        <div className="section-header text-center" style={{ marginBottom: "50px" }}>
          <span className="section-subtitle">FAQ</span>
          <h2 className="section-title">Frequently Asked Questions</h2>
          <p className="section-desc">
            Find answers to core legal, booking, customization, and timeline details.
          </p>
        </div>

        <div style={{ display: "grid", gap: "20px" }}>
          {faqData.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div 
                key={idx} 
                className="faq-card"
                style={{
                  backgroundColor: "var(--bg-surface)",
                  border: "1px solid var(--border-color)",
                  padding: "24px",
                  transition: "var(--transition-smooth)"
                }}
              >
                <button
                  onClick={() => toggleFAQ(idx)}
                  style={{
                    width: "100%",
                    background: "transparent",
                    border: "none",
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    textAlign: "left",
                    cursor: "pointer",
                    padding: 0,
                    fontFamily: "var(--font-serif)",
                    fontSize: "20px",
                    fontWeight: 600,
                    color: "var(--text-white)",
                    transition: "color 0.2s ease"
                  }}
                >
                  <span style={{ color: "#000000" }}>{faq.question}</span>
                  <span style={{ 
                    fontSize: "24px", 
                    lineHeight: "1", 
                    color: "#000000",
                    transform: isOpen ? "rotate(45deg)" : "rotate(0deg)",
                    transition: "transform 0.25s ease",
                    marginLeft: "15px"
                  }}>
                    +
                  </span>
                </button>
                
                <div 
                  style={{
                    maxHeight: isOpen ? "300px" : "0px",
                    overflow: "hidden",
                    opacity: isOpen ? 1 : 0,
                    transition: "max-height 0.35s cubic-bezier(0.16, 1, 0.3, 1), opacity 0.35s ease",
                    marginTop: isOpen ? "15px" : "0px"
                  }}
                >
                  <p style={{ 
                    color: "var(--text-muted)", 
                    fontSize: "16px", 
                    lineHeight: "1.7",
                    margin: 0,
                    fontWeight: 400 
                  }}>
                    {faq.answer}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
